### ISSUE TITLE
Invalid Visualization Error Qlik Sense April 2019 Version

### ISSUE THREAD

**Issue by ashipp2010** [SirGarnet/qlik-sense-timeline#2]
After installing on April 2019 version of Qlik Sense. Extension throws the following error: "Invalid Visualization: the visualization was not found on the server. The extension is not available.".

**Comment by SirGarnet** [comment]
So there is a new version, take a look it should work now.

Problem war the deprecation of the moment library

**Comment by vissu430** [comment]
> So there is a new version, take a look it should work now.
> 
> Problem war the deprecation of the moment library

Thank you for fixing the bug.

**Comment by tmcwilliams-axis** [comment]
Hi,

We are seeing this issue intermittently using version 1.7 of this extension. We had been using it for around a year with no issues and it was noticed on May 4th for the first time. We upgraded the extension to 1.7 and have still seen occurrences of it although not as frequent. We are running QS June 2019 Patch 8.

**Comment by SirGarnet** [comment]
Hi I will check this with our setup. Stay tuned for updates. Did you tried to drag drop a new instance to your sheet? Is there the same problem?

RegardsFlow

**Comment by tmcwilliams-axis** [comment]
We tried removing the extension and adding it again but the same error appears. I have included a screenshot below of what we are seeing. This error isn't consistent and only appears on occasion. If there is anything else that would help you diagnose this issue please let me know.

![image](https://user-images.githubusercontent.com/65247433/81957479-9eed9180-95da-11ea-9493-6eb7e8d6ae48.png)

**Comment by SirGarnet** [comment]
Hi,

for me it looks like a broken path. Can you check in the developer 
tools, if there is a 404 for an URL that should map to the module name?

Thanks
Flow

**Comment by SirGarnet** [comment]
Hi,

I've checked our server. It is running with Qlik Sense June 2019 - 13.32.2 and it is running fine so far.

Did you set the extension to readable (R) for the users after uploading it to the server?

Regards
Flow

**Comment by tmcwilliams-axis** [comment]
We have a rule that allows everyone the ability to read all extensions so I don't think that is it. It also happens to us intermittently so it is not a constant error message.

When I try opening the extension in the dev hub I get an error about the "wbfolder.wbl" file missing so I am unable to dig any further into that 
![image](https://user-images.githubusercontent.com/65247433/82070783-3c13fd00-96a3-11ea-8105-a8aba5c67ea3.png)

![image](https://user-images.githubusercontent.com/65247433/82070929-65cd2400-96a3-11ea-9fea-716ee47e3c7e.png)

**Comment by SirGarnet** [comment]
I've added a wbfolder.wbl to the repository

Still trying to get a server with latest June 2019 Patch 8 for testing, need to allign it with our company.

**Comment by tmcwilliams-axis** [comment]
Sounds good, I uploaded the new version to our environments and it seems to be working for now. Would it help to set up a remote session when/if we notice it happening again so you can see it firsthand?
