### ISSUE TITLE
extetion not working on SaaS

### ISSUE THREAD

**Issue by hvfalcao** [SirGarnet/qlik-sense-timeline#4]
I'm having an issue with the google timeline on Sense Cloud Service on async.js file probably...

On SaaS, security is managed by Content Security Policy. For external source we need to allow domain and directives. 'script-src' is available, but 'script-src-elem' is not.

https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Admin/mc-administer-content-security-policy.htm

Script Error when loading...

async.js:15 Refused to load the script 'https://www.google.com/jsapi?callback=__async_req_1__' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' maps.qlikcloud.com cdn.qlikcloud.com requirejs.org google.com gstatic.com momentjs.com". **Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.**

**Comment by SirGarnet** [comment]
Hi,

Currently I have no SaaS available for testing. Did you tryed to create directive for https/http + ://www.google.com/jsapi

Could solve the problem.

**Comment by hvfalcao** [comment]
Found the problem... instead of using only google.com in the CSP as mentioned on Sense Help, I should use WWW.google.com 

Thanks!

**Comment by hvfalcao** [comment]
You might wanna add this rule for SaaS users...

Go to Content Security Polices and add as img bellow for this src...

1 - ajax.googleapis.com
2 - google.com

![image](https://user-images.githubusercontent.com/5053785/82849732-95fc9a00-9ecf-11ea-8de4-fbe223b70a42.png)

**Comment by SirGarnet** [comment]
Hi I've just updated the extension to fix the invalid extension bug. Maybe someone likes to try and give some feedback? Thanks in advanced.

**Comment by hvfalcao** [comment]
> Hi I've just updated the extension to fix the invalid extension bug. Maybe someone likes to try and give some feedback? Thanks in advanced.

Hi... the problem returned as mentioned into other issues last weeks... Updated with 1.8, but problem persists... have you added any other source that I should add to the CSP?

**Comment by SirGarnet** [comment]
I only added the one that is mentioned in the readme, did you tried that one?

**Comment by hvfalcao** [comment]
yeppp... sorry about that... I din't read the readme before! sorry... its running perfect now... thank you!

**Comment by SirGarnet** [comment]
Good that this problem is solved, have fun with the extension.
